image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

build:
  stage: build
  script:
    gradle build -x checkstyleMain -x checkstyleTest -x pmdMain -x pmdTest -x test

checkStyle:
  stage: staticAnalysis
  script:
    gradle checkstyleMain checkstyleTest

PMD:
  stage: staticAnalysis
  script:
    gradle pmdMain pmdTest

test:
  stage: test
  script:
    - gradle test codeCoverageReport
    - cat build/reports/jacoco/codeCoverageReport/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
