image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

build:
  stage: build
  script:
    gradle build -x checkstyleMain -x checkstyleTest -x pmdMain -x pmdTest

checkStyle:
  stage: staticAnalysis
  script:
    gradle checkstyleMain checkstyleTest

PMD:
  stage: staticAnalysis
  script:
      gradle pmdMain pmdTest

test:
  stage: test
  script:
    gradle test
